variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'  

stages:
  - build
  - test
  - release
  - notify
  - deploy

build:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - >
      docker build
      --build-arg VERSION=$VERSION
      --tag $CI_REGISTRY_IMAGE/momo-frontend:$VERSION
      .
    - docker push $CI_REGISTRY_IMAGE/momo-frontend:$VERSION

sonarqube-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  needs:
    - build
  script:
    - cd frontend
    - >
      sonar-scanner
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_FRONT}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_FRONT} 
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectName=17_YURIKRYVINYA_MOMO_FRONT

spotbugs-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository         

upload-frontend-latest:
  variables:
    GIT_STRATEGY: none
  image: docker:20.10.12-dind-rootless
  stage: release
  needs:
    - build
    - sonarqube-sast
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/momo-frontend:$VERSION
    - docker tag $CI_REGISTRY_IMAGE/momo-frontend:$VERSION $CI_REGISTRY_IMAGE/momo-frontend:latest
    - docker push $CI_REGISTRY_IMAGE/momo-frontend:latest

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config set-cluster momo-cluster --server="https://51.250.5.173"
    - kubectl config set clusters.momo-cluster.certificate-authority-data "${KUBE_CERTIFICATE_AUTHORITY}"
    - kubectl config set-credentials kyn07c0 --token="eyJhbGciOiJSUzI1NiIsImtpZCI6ImdUWklHV2lFVGdteWRGMjltbWdSS2RZcFJPcDhlLVI2b2pDQ1JrRHlpamcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwZTQ2YWU4ZC1jMTUzLTQ4NmUtOWYzNC1mMjNmMzMzOTg2MWQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YWRtaW4tdXNlciJ9.Y3AHv6hIQYz9R7FfuQ_WQrb_LCqihJhtFFJSvZS5I5uu1pAeWD5Sl3Hx_i2qGYJeG9eojaAgMrKdU8q4z_ugjNbWzPR3lWYdjxBzDupHLer-gY4af9vDrBraOC2NuHNmza6aCwdIeDO7EWQxEW-Pf99ETwHwO8Iylkl9ldlXCyQjVWZoLTKs3310ijovPbiMmnFuHSAaxHzz_Ge-Kv3AB17t9RNugbJmi9i6wcukkUSdXOzRI5m6rhW-P4U82m6UirYHP96o1FkyDiT9EvVbJPae6Z2nVp-RkfTQMP7jgfmKpa2Yf9DOrVXKEWJZ86Oa-htEa2P3zbDCvmdSTEbrVA"
    - kubectl config set-context kyn07c0@momo-cluster --cluster=momo-cluster --user=kyn07c0
    - kubectl config use-context kyn07c0@momo-cluster
    - kubectl apply -f kubernetes/frontend
