---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  nginx.conf: |
    upstream myproxy {
      server backend:8081;
    }

    server {
        listen {{ .Values.containerPort }};

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://myproxy/;
        }

    }
