---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 3
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 80%
      maxSurge: 20%
  selector:
    matchLabels:    
      app: backend
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gitlab.praktikum-services.ru:5050/std-017-006/momo-store/momo-backend:latest
        imagePullPolicy: Always
        ports:
        - name: backend
          containerPort: 8081
      imagePullSecrets:
      - name: docker-config-secret

