apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: momo-cert
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kyn07c0@yandex.ru
    privateKeySecretRef:
      name: momo-cert
    solvers:
    - http01:
        ingress:
          class: nginx
