stages:
  - release
  - deploy

variables:
  CHART_VERSION: 0.1.${CI_PIPELINE_IID}

release-helm-chart:
  stage: release
  image: alpine/helm:3.10.0
  script:
    - cd kubernetes
    - helm package momo-store-chart --version $CHART_VERSION
    - curl -u ${NEXUS_HELM_USER}:${NEXUS_HELM_PASS} --upload-file momo-store-${CHART_VERSION}.tgz ${NEXUS_HELM_REPO}

install-helm-chart:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  image: alpine/helm:3.10.0
  script:
    - mkdir ~/.kube
    - echo "${KUBE_CONFIG}" > ~/.kube/config
    - helm repo add nexus ${NEXUS_HELM_REPO} --username ${NEXUS_HELM_USER} --password ${NEXUS_HELM_PASS}
    - helm repo update
    - >
      helm upgrade --atomic -i
      --set dockerconfigjson="${DOCKERCONFIGJSON}"
      momo-store nexus/momo-store --version $CHART_VERSION
