variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - helm-release
  - helm-install
    
release-helm-chart:
  stage: helm-release
  image: alpine/helm:latest
  script:
    - sed -i "s/{{VERSION}}/${VERSION}/g" helm/backend/Chart.yaml
    - helm package helm/backend --version ${VERSION}
    - curl -u ${NEXUS_HELM_USER}:${NEXUS_HELM_PASS} ${NEXUS_HELM_REPO_BACKEND} --upload-file backend-${VERSION}.tgz

install-helm-chart:
  variables:
    GIT_STRATEGY: none
  stage: helm-install
  image: alpine/helm:latest
  before_script:
    - mkdir ~/.kube
    - echo "${KUBE_CONFIG}" > ~/.kube/config
    - chmod go-r ~/.kube/config
  script:
    - helm repo add nexus ${NEXUS_HELM_REPO_BACKEND} --username ${NEXUS_HELM_USER} --password ${NEXUS_HELM_PASS}
    - helm repo update
    - helm upgrade backend nexus/backend -i --atomic --set image.tag=$VERSION --namespace default
