variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
    
stages:
  - deploy

deploy:
  image: dtzar/helm-kubectl:3.13.0
  stage: deploy
  script:
    - kubectl config set-cluster ${KUBE_CLUSTER} --server="${KUBE_SERVER}" --insecure-skip-tls-verify=true
    - kubectl config set-credentials ${KUBE_USER} --token="${KUBE_TOKEN}"
    - kubectl config set-context ${KUBE_USER}@${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user="${KUBE_USER}"
    - kubectl config use-context ${KUBE_USER}@${KUBE_CLUSTER}
    - helm repo add nexus ${NEXUS_HELM_REPO} --username ${NEXUS_HELM_USER --password ${NEXUS_HELM_PASS}
    - helm repo update
    - helm upgrade momo-store-backend nexus/momo-store-backend -i --atomic
