---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: default
  labels:
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
      nodePort: 30081
  selector:
    app: {{ .Chart.Name }}
