image:
  repository: gitlab.praktikum-services.ru:5050/std-017-006/momo-store/momo-frontend
  pullPolicy: Always
  tag: {{TAG}}
replicas: 1
revisionHistoryLimit: 15
strategy:
  type: RollingUpdate
containerPort: 80
host: kyn07c0.ru
